---
apiVersion: v1
items:
- metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"webapp-argo"},"name":"fleetman-webapp","namespace":"webapp-argo"},"spec":{"ports":[{"name":"http","nodePort":30081,"port":80}],"selector":{"app":"webapp"},"type":"NodePort"}}
    creationTimestamp: "2024-01-17T10:59:58Z"
    labels:
      app.kubernetes.io/instance: webapp-argo
    name: fleetman-webapp
    namespace: webapp-argo
    resourceVersion: "689135"
    uid: 3a189fa3-2372-4de8-8db9-a0cd91c5015b
  spec:
    clusterIP: 10.107.229.152
    clusterIPs:
    - 10.107.229.152
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30081
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: webapp
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer:
      ingress:
      - hostname: localhost
kind: ServiceList
metadata:
  resourceVersion: "693287"
