---
apiVersion: apps/v1
items:
- metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"portainer-agent","namespace":"portainer"},"spec":{"selector":{"matchLabels":{"app":"portainer-agent"}},"template":{"metadata":{"labels":{"app":"portainer-agent"}},"spec":{"containers":[{"env":[{"name":"LOG_LEVEL","value":"DEBUG"},{"name":"AGENT_CLUSTER_ADDR","value":"portainer-agent-headless"},{"name":"KUBERNETES_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"portainer/agent:2.19.4","imagePullPolicy":"Always","name":"portainer-agent","ports":[{"containerPort":9001,"protocol":"TCP"}]}],"serviceAccountName":"portainer-sa-clusteradmin"}}}}
    creationTimestamp: "2024-01-11T11:48:38Z"
    generation: 1
    name: portainer-agent
    namespace: portainer
    resourceVersion: "678676"
    uid: 068e8472-5e8a-4076-b302-37a0454200f1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: portainer-agent
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: portainer-agent
      spec:
        containers:
        - env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: AGENT_CLUSTER_ADDR
            value: portainer-agent-headless
          - name: KUBERNETES_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          image: portainer/agent:2.19.4
          imagePullPolicy: Always
          name: portainer-agent
          ports:
          - containerPort: 9001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: portainer-sa-clusteradmin
        serviceAccountName: portainer-sa-clusteradmin
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-01-11T11:48:38Z"
      lastUpdateTime: "2024-01-11T11:48:40Z"
      message: ReplicaSet "portainer-agent-548d57f7b5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-01-17T08:59:08Z"
      lastUpdateTime: "2024-01-17T08:59:08Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: DeploymentList
metadata:
  resourceVersion: "693285"
